const baseDatosIPD = [
  {
    fecha: "2026-10-09",
    jurisdiccion: "nacion",
    titulo: "Resolución 69/2026",
    criollo: "La resolución dice que actualiza la normativa de gestión aeroportuaria para mejorar la seguridad y la eficiencia. Pero en realidad abre la puerta a nuevas concesiones privadas, favoreciendo a Aeropuertos Argentina 2000 y a grupos vinculados al sector energético, al reducir requisitos de licitación y permitir acuerdos de autoprestación. La trampa está en el artículo 12, que delega al regulador la potestad de fijar tarifas sin control parlamentario. Otra vez sopa.",
    letraChica: "El artículo 12 delega al organismo la facultad de fijar tarifas aeroportuarias sin control ni licitación, permitiendo que Aeropuertos Argentina 2000 ajuste precios a su conveniencia.",
    articulo: "Modernización o entrega: la Resolución 69/2026 que reescribe el juego de los aeropuertos\n\nEl Gobierno anuncia una \"actualización normativa\" para los aeropuertos nacionales, con la promesa de mayor seguridad, eficiencia y competitividad. Un discurso que suena a progreso, pero que esconde la verdadera jugada.\n\nEl texto dice que se simplifican los procedimientos de autorización, se reducen cargas burocráticas y se fomenta la inversión privada para modernizar la infraestructura. En la práctica, la medida recorta los requisitos de licitación, permite la autoprestación de servicios y otorga al Organismo Regulador la facultad de fijar tarifas sin ningún control parlamentario ni de la sociedad civil.\n\n¿A quién le sirve? A los grandes grupos que ya manejan la mayor parte del tráfico aéreo, como Aeropuertos Argentina 2000, y a consorcios energéticos que buscan integrar servicios de combustible y logística. La eliminación de la licitación abre la puerta a acuerdos bajo la mesa, donde los precios y condiciones se negocian entre el regulador y los operadores, sin transparencia.\n\nLos beneficiarios directos son los accionistas de Aeropuertos Argentina 2000, los conglomerados de energía que pueden vender combustible a precios preferenciales y los bancos que financian estas concesiones bajo condiciones ventajosas. El mecanismo de apropiación es claro: la renta que antes generaba el Estado por la gestión de pistas, terminales y tarifas de aterrizaje pasa a manos privadas, mientras que el Estado se queda con la carga de la regulación sin recursos para fiscalizar.\n\nEl impacto social es devastador. Los trabajadores de los aeropuertos pierden la garantía de empleo estable y los convenios colectivos se ven amenazados por la flexibilización laboral que acompañará a la privatización. Los usuarios finales verán aumentos de tarifas sin justificación, ya que el nuevo régimen permite al regulador fijar precios sin auditoría. Además, la pérdida de control estatal debilita la soberanía del país sobre una infraestructura estratégica para el comercio y la defensa.\n\nLa trampa está en el artículo 12, que otorga al organismo la potestad de fijar tarifas aeroportuarias sin control ni licitación. Ese párrafo, escondido al final del documento, es la verdadera entrega: convierte a los aeropuertos en un bien de mercado, alejado del control popular y del Estado empresario.\n\n¿Quién paga la cuenta? El trabajador del sector, el viajero argentino y la Nación que pierde una fuente de ingresos estratégicos. La modernización anunciada no es más que una fachada para la privatización encubierta de los aeropuertos. Como siempre."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Resolución 127-SSTAYLMAMGP-2026",
    criollo: "El texto dice que la Resolución 127 autoriza la Licitación Pública 6/2026 para comprar molinos, agrumadora y demás equipos del programa “Mi Provincia Recicla”, impulsando la economía circular y el trabajo de los recuperadores urbanos. Pero en realidad abre la puerta a empresas del rubro que ya aparecen en los presupuestos, sin exigencia de competencia real, permitiendo sobreprecios y la captura del gasto público. La trampa está en el artículo 1 y el pliego, que autoriza la licitación sin controles de adjudicación y favorece a los proveedores preseleccionados. Otra vez sopa.",
    letraChica: "El artículo 1 autoriza la licitación sin exigir competencia real y el pliego de bases permite adjudicación a empresas preseleccionadas, garantizando la entrega del presupuesto de $625.781.536 a los proveedores sin control de precios.",
    articulo: "Licitar la basura: ¿quién se lleva el dinero del reciclaje?\n\nLa Resolución 127‑SSTAYLMAMGP‑2026 anuncia una licitación para equipar la economía circular, pero la realidad es una jugada de los proveedores de maquinaria.\n\nEl texto dice que la medida autoriza la Licitación Pública N° 6/2026 para adquirir molinos, agrumadora, elevadores, secador, balanzas, enfardadoras y cintas de clasificación, con el objetivo de fortalecer la gestión de residuos sólidos urbanos, crear empleo para los recuperadores y promover la valorización de materiales. Se menciona un presupuesto de $625.781.536 y se cita la Ley 13.981 como marco legal.\n\nPero en la práctica la resolución se limita a publicar una lista de “presupuestos de diversas firmas del rubro comercial” sin detallar criterios de selección, sin exigir licitación competitiva y sin establecer mecanismos de control de precios. La autoridad que firma, el Subsecretario Técnico del Ministerio de Ambiente, delega la contratación a la Subsecretaría de Residuos Sólidos Urbanos y Economía Circular, que ya cuenta con contactos estrechos con los proveedores. El proceso favorece a los grandes distribuidores de equipos de reciclaje, que podrán inflar precios y captar recursos públicos sin que el Estado garantice la mejor oferta ni la generación de empleo real.\n\nLa trampa está en el artículo 1 y en el Pliego de Bases y Condiciones Particulares, que autoriza la licitación sin exigir una competencia real y permite la adjudicación a empresas preseleccionadas. Además, la “inclusión social” proclamada en el sumario queda en la letra chica: no hay cláusulas que obliguen a contratar mano de obra local ni a destinar parte del presupuesto a cooperativas de recuperadores. El gasto público se transforma en rentabilidad privada.\n\n¿A quién le sirve? A los proveedores de maquinaria que ya aparecen en los presupuestos y a los funcionarios que facilitan la adjudicación. ¿Quién paga? El contribuyente de la Provincia de Buenos Aires y, en última instancia, los trabajadores del sector que no ven mejoras salariales ni estabilidad laboral. Como siempre."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Decreto N° 90/2022",
    criollo: "El decreto dice que el turismo es estratégico y que el Ministerio de Producción, Ciencia e Innovación Tecnológica diseñará políticas para su desarrollo. Pero en realidad concentra la autoridad en un solo organismo, elimina controles locales y permite delegar la gestión de parques y playas a empresas privadas sin licitación. La trampa está en el artículo 9, que autoriza convenios con grandes cadenas hoteleras y promotores inmobiliarios, desviando rentas públicas al sector privado. Otra vez sopa.",
    letraChica: "En el artículo 9 se autoriza la delegación de la gestión de recursos turísticos a empresas privadas mediante convenios sin licitación, garantizando que los ingresos generados terminen en los balances de grandes cadenas hoteleras e inmobiliarias.",
    articulo: "Turismo bajo la lupa: el decreto que vende la provincia a los grandes grupos\n\nEl Decreto 90/2022 se presenta como impulso al turismo provincial, pero abre la puerta a la privatización de recursos y a la captura de rentas por parte de gigantes hoteleros.\n\nEl texto dice que el turismo es de interés provincial, esencial y estratégico, y que el Ministerio de Producción, Ciencia e Innovación Tecnológica diseñará y ejecutará políticas de ordenamiento, promoción y desarrollo. La fórmula oficial suena a planificación democrática y a generación de empleo.\n\nPero en la práctica la norma concentra la autoridad en un solo organismo, elimina los controles locales y permite la delegación de la gestión de parques, playas y destinos turísticos a empresas privadas sin licitación. Se crea un marco que favorece la firma de convenios con grandes cadenas hoteleras internacionales y con grupos inmobiliarios que buscan desarrollar complejos turísticos de alto nivel.\n\nLa trampa está en el artículo 9, que autoriza la celebración de convenios de gestión turística con fondos privados, sin requisitos de transparencia ni licitación previa. Ese artículo permite que los ingresos generados por la actividad turística –entradas, tasas, servicios– terminen en los balances de empresas como Marriott, Hilton o promotores inmobiliarios locales, en lugar de reinvertirse en la comunidad.\n\nBeneficiarios directos: los grandes grupos hoteleros internacionales, los consorcios inmobiliarios que construyen resorts y centros de convenciones, y las agencias de viajes que operan bajo contratos preferenciales. Mecanismo de apropiación: transferencia de rentas mediante convenios sin licitación, eliminación de la fiscalización provincial y creación de fondos privados que absorben los recursos.\n\nImpacto social: los trabajadores del sector pierden estabilidad, los pequeños operadores y hosterías quedan fuera del mercado, y la provincia pierde soberanía sobre sus recursos turísticos. La promesa de empleo se transforma en empleo precario bajo contratos temporales y en la pérdida de ingresos para los municipios.\n\n¿A quién le sirve? A los grandes capitales que buscan rentas rápidas. ¿Quién paga? El trabajador del sector, el turista que paga precios inflados y la comunidad que pierde recursos. Como siempre."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Decreto N° 312/25",
    criollo: "El decreto dice que impulsa el desarrollo productivo del Sudoeste bonaerense con financiamiento no reintegrable del 50% del costo del proyecto. Pero en realidad canaliza recursos públicos a grandes agroholdings y a la Corporación de Fomento del Valle del Río Colorado, dejando fuera a los pequeños productores que no pueden cumplir con los requisitos técnicos. La trampa está en el artículo que limita el uso del aporte a inversiones de capital y prohíbe gastos corrientes, obligando a que la mayor parte del beneficio recaiga en quienes ya tienen capacidad de inversión. Otra vez sopa.",
    letraChica: "El artículo 5 del decreto establece que los aportes no reintegrables solo pueden destinarse a inversiones de capital, excluyendo gastos operativos y limitando la ayuda a quienes ya disponen de fondos propios.",
    articulo: "Finanzas con letra pequeña: el Decreto 312/25 que promete desarrollo al Sudoeste bonaerense\n\nEl Gobierno provincial lanza el Decreto N° 312/25 como la solución milagrosa para “articular el trabajo” entre el Consejo Regional y el Ministerio y financiar proyectos agropecuarios. La fórmula suena generosa: aportes no reintegrables cubriendo el 50% del costo, con un techo de 20 millones por iniciativa.\n\nEl texto dice que se trata de una herramienta para fortalecer la matriz socio‑económica, impulsar PyMEs, emprendedores y la capacitación. Pero la realidad es otra. Los requisitos de capacidad técnica, presentación de proyectos de capital y la prohibición de usar los fondos para gastos corrientes convierten la ayuda en un privilegio para los grandes agroholdings y para la Corporación de Fomento del Valle del Río Colorado, que ya cuentan con equipos de gestión y acceso a crédito. Los pequeños productores, que carecen de personal para armar expedientes y de fondos propios para cubrir la otra mitad del costo, quedan fuera del juego.\n\n¿A quién le sirve? A los conglomerados agroindustriales que pueden absorber la mitad del financiamiento y usar el resto como subsidio encubierto, aumentando su capacidad de producción sin crear empleo real. ¿Quién paga? El contribuyente provincial, que ve cómo su dinero se destina a proyectos que ya generan rentas para empresas con capacidad de exportar.\n\nLa trampa se esconde en el artículo 5, que limita el uso del aporte a inversiones de capital y prohíbe cualquier gasto corriente. Esa cláusula obliga a que la ayuda solo beneficie a quien ya posee recursos para financiar la operación diaria, mientras los laburantes del campo siguen sin empleo ni salarios dignos.\n\nEn conclusión, el decreto no es una política de desarrollo inclusivo, sino una redistribución de recursos públicos a los que ya tienen la capacidad de invertir. El pueblo trabajador sigue esperando la verdadera generación de empleo y la industrialización local que la norma promete pero nunca entrega. Así estamos."
  },
];
