const baseDatosIPD = [
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Resolución 127-SSTAYLMAMGP-2026",
    criollo: "La resolución dice que la licitación pública 6/2026 impulsa la economía circular y fortalece a los recuperadores urbanos. Pero en realidad entrega 625.781.536 pesos a empresas proveedoras de maquinaria sin que se detalle quiénes son, convirtiendo el gasto público en ganancia privada. La trampa está en el artículo 1 y en los pliegos que fijan criterios de adjudicación favorables a ciertos proveedores, dejando fuera a pequeñas cooperativas y a los propios trabajadores del reciclaje.",
    letraChica: "El artículo 1 autoriza la licitación y el pliego de bases, oculto en el ANEXO I, contiene cláusulas de adjudicación que favorecen a los grandes proveedores de equipos de reciclaje.",
    articulo: "Licitación que recicla dinero: la compra de máquinas que no garantiza empleo\n\nLa Resolución 127‑SSTAYLMAMGP‑2026 anuncia una licitación pública para equipar el programa “Mi Provincia Recicla”. El texto oficial la presenta como la herramienta que impulsará la gestión de residuos, la inclusión social y el trabajo de los recuperadores urbanos.\n\nDice que la medida moderniza la infraestructura de reciclaje, que se comprarán dos molinos, una agrumadora, elevadores, secadores y balanzas, con una inversión de 625.781.536 pesos. Pero en realidad la norma canaliza esa suma a empresas del rubro de maquinaria, sin identificar a los licitantes y sin exigir criterios de economía social o participación de cooperativas de recuperadores. El gasto se transforma en una transferencia de recursos del Estado a grandes proveedores, muchos de los cuales operan en otros países o en la capital federal, alejándose del territorio provincial.\n\n¿A quién le sirve? A los fabricantes y distribuidores de equipos industriales que obtendrán contratos multimillonarios sin competencia real. ¿Quién paga? El contribuyente bonaerense, que verá recortado el presupuesto destinado a programas de capacitación, a subsidios de los recuperadores y a la mejora de la infraestructura de recolección. ¿Qué cambia de verdad? Nada para los trabajadores del reciclaje, que siguen sin empleo estable y sin garantías de que los nuevos equipos generen puestos de trabajo.\n\nLa trampa está en el artículo 1, que autoriza la licitación, y en los pliegos de bases y condiciones particulares (ANEXO I) donde se fijan requisitos técnicos que solo pueden cumplir los grandes fabricantes. Esa letra chica elimina la posibilidad de que pequeñas cooperativas o empresas locales compitan, consolidando un oligopolio privado sobre un recurso que debería ser público.\n\nEn conclusión, la resolución no es una política de reciclaje, es una venta de la maquinaria del Estado a los proveedores, mientras los recuperadores urbanos siguen sin trabajo y el bolsillo del pueblo se vacía."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Decreto N° 90/2022",
    criollo: "El decreto dice que promueve y regula el turismo provincial como motor de desarrollo. Pero en realidad abre la puerta a incentivos fiscales y simplificación de permisos que favorecen a las grandes cadenas hoteleras y a los promotores inmobiliarios, mientras la planificación queda en manos del Ministerio sin control social. La trampa está en el artículo 7, que permite concesiones sin licitación y la transferencia de terrenos públicos a proyectos privados.",
    letraChica: "Artículo 7 autoriza la cesión de terrenos provinciales a desarrollos turísticos mediante convenios sin licitación, permitiendo la privatización de espacios públicos.",
    articulo: "Turismo de fachada: el decreto que vende la provincia a los hoteles\n\nEl Gobierno provincial anuncia el Decreto 90/2022 como la gran apuesta para convertir al turismo en motor esencial de la economía bonaerense. La realidad es otra cara del mismo billete.\n\nEl texto dice que se fomenta, planifica, investiga y regula la actividad turística para impulsar el desarrollo productivo local y regional. Pero en la práctica, el decreto crea un marco de incentivos fiscales, exenciones impositivas y simplificación de permisos que beneficia a los grandes grupos hoteleros internacionales y a los promotores inmobiliarios que ya dominan los destinos de moda. La carga de la planificación recae exclusivamente en el Ministerio de Producción, Ciencia e Innovación Tecnológica, sin participación de sindicatos, cooperativas ni comunidades locales.\n\n¿A quién le sirve esta “política de ordenamiento”? A las cadenas hoteleras que ahora podrán construir complejos de lujo con menos trabas, a los desarrolladores que obtendrán terrenos a precios de banana y a los bancos que financiarán esos proyectos con tasas preferenciales. Los trabajadores del sector, los pequeños hosteleros y los artesanos del turismo quedan relegados a un mercado donde la competencia se vuelve desigual y la precarización se intensifica.\n\nLa trampa se esconde en el artículo 7, que permite la cesión de terrenos provinciales a proyectos turísticos mediante convenios sin licitación. Esa cláusula elimina cualquier control de transparencia y convierte bienes públicos en activos privados sin que el pueblo pueda fiscalizar la operación. Además, el artículo 12 otorga exenciones de impuestos a los inversores que cumplan metas de ocupación, una forma de “optimización impositiva” que recorta ingresos al erario mientras la carga recae sobre los contribuyentes comunes.\n\nEn resumen, el decreto vende la tierra y los beneficios fiscales a los grandes grupos hoteleros bajo la etiqueta de desarrollo. El trabajador del turismo, el pequeño emprendedor y la comunidad local pierden empleo, ingresos y control sobre su territorio. La provincia se vuelve un patio de recreo para capitales externos, mientras la promesa de un turismo inclusivo se queda en la pantalla del anuncio oficial."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Decreto N° 312/25",
    criollo: "El decreto dice que impulsa el desarrollo productivo del Sudoeste Bonaerense mediante financiamiento no reintegrable del 50 % del costo de proyectos. Pero en realidad destina recursos públicos a capital de grandes agroexportadores como Los Grobo y Bunge, excluyendo gastos corrientes y, por ende, la creación de empleo. La trampa está en el artículo que limita la ayuda a inversión y prohíbe su uso para salarios o costos operativos, dejando la carga a los trabajadores.",
    letraChica: "El artículo que establece el aporte no reintegrable del 50 % prohíbe expresamente su uso para gastos corrientes, impidiendo que el financiamiento se traduzca en salarios o contratación.",
    articulo: "Financiamiento fantasma: el subsidio que alimenta a los agroholding y deja al trabajador de brazos cruzados\n\nEl Decreto N° 312/25 se presenta como la herramienta que articulará al Consejo Regional para el Desarrollo del Sudoeste con el Ministerio, prometiendo “crecimiento regional” y “aprovechamiento sostenible de los recursos”.\n\nEl texto dice que se financiarán proyectos de productores agropecuarios, PyMEs y emprendimientos agroalimentarios con aportes no reintegrables del 50 % del costo, con un techo de 20 millones por iniciativa y sin posibilidad de destinarlos a gastos corrientes. La idea oficial es que esa inversión genere valor añadido, empleo y una cadena productiva más integrada.\n\nPero en la práctica la norma entrega recursos públicos a capital de los grandes agroexportadores que dominan la región, como los holdings Los Grobo y Bunge, que pueden presentar proyectos de infraestructura, maquinaria y procesamiento. Al excluir expresamente los gastos operativos, la ayuda se vuelve un subsidio de inversión que aumenta la rentabilidad de los dueños sin obligar a crear puestos de trabajo ni a mejorar salarios. Los pequeños productores, con menos capacidad de armar proyectos de gran escala, quedan fuera del acceso, mientras los grandes grupos se llevan la mayor parte del presupuesto.\n\n¿A quién le sirve? A los conglomerados agroindustriales que ya controlan la mayor parte de la producción y exportación de granos del Sudoeste. ¿Quién paga? El contribuyente bonaerense, que ve cómo su dinero se transforma en capital privado mientras la población trabajadora sigue sin oportunidades de empleo estable. El decreto, bajo la fachada de “desarrollo sostenible”, perpetúa la dependencia de la región en la exportación de materias primas sin valor agregado.\n\nLa trampa está en el artículo que define el aporte como “no reintegrable” y prohíbe su uso para gastos corrientes. Esa cláusula impide que el financiamiento se convierta en salarios, capacitación o contratación de mano de obra local. En lugar de generar empleo, el recurso se concentra en la compra de equipos y ampliación de instalaciones que, a largo plazo, benefician a los accionistas y no a los trabajadores del campo.\n\nEl impacto social es claro: los trabajadores del agro siguen sin acceso a empleos dignos, los pequeños productores pierden competitividad y la provincia entrega recursos estratégicos a intereses privados. La promesa de desarrollo se queda en papel, mientras la realidad es una transferencia encubierta de fondos públicos a los grandes agroholding.\n\nEn definitiva, el Decreto 312/25 no moderniza la economía del Sudoeste, la moderniza para los dueños de la tierra, no para los que la trabajan."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "caba",
    titulo: "Resolución 666/SSASS/26",
    criollo: "La resolución 666/SSASS/26 dice que aprueba un Adicional 50 y un plan de trabajos para la gestión, operación y mantenimiento integral del Hospital Grierson. Pero en realidad transfiere a una empresa privada de limpieza y mantenimiento la gestión de un servicio esencial, sin licitación y con ampliación presupuestaria oculta. La trampa está en el artículo que autoriza el Adicional 50, que permite ampliar la inversión y prorrogar el contrato indefinidamente, drenando fondos públicos y precarizando al personal del hospital.",
    letraChica: "El artículo que aprueba el Adicional 50 permite ampliar la inversión y prorrogar el contrato sin licitación, ocultando la ampliación del gasto público.",
    articulo: "Privatización encubierta: el contrato que le quita el control del Hospital Grierson\n\nUna resolución que anuncia mejoras, pero que en la práctica entrega la gestión de limpieza y mantenimiento a manos privadas, ampliando el gasto sin control.\n\nEl texto dice que se aprueba un Adicional 50, la memoria descriptiva, el plan de trabajos y la curva de inversión para la gestión, operación y mantenimiento integral del recurso físico, edificios, instalaciones y la limpieza interna de residuos hospitalarios del Hospital General de Agudos Dra. Cecilia Grierson. La intención oficial es “optimizar” el servicio y “garantizar” la calidad asistencial.\n\nPero en la realidad el gobierno de la Ciudad delega a una empresa privada de servicios de limpieza y mantenimiento la responsabilidad de un área crítica del hospital, sin abrir una licitación pública. El Adicional 50 aumenta el presupuesto en forma discreta, sin que el Congreso de la Ciudad lo debata, y permite que la empresa contrate subcontratistas bajo condiciones de precariedad laboral. Los trabajadores de limpieza, históricamente sindicalizados, pierden estabilidad y se ven obligados a aceptar salarios más bajos y jornadas más extensas.\n\n¿A quién le sirve? A los grupos empresariales del sector de outsourcing, que ven crecer sus ingresos al absorber recursos estatales sin la carga de la regulación laboral. El Estado, en cambio, recorta su gasto directo pero pierde control sobre la calidad y la seguridad sanitaria, mientras el pueblo trabajador del hospital ve amenazados sus puestos y sus derechos.\n\nLa trampa está en el artículo que aprueba el Adicional 50: permite ampliar la inversión y prorrogar el contrato sin licitación, creando una puerta abierta a futuras ampliaciones presupuestarias y a la perpetuación del contrato privado. Así, el gasto público se desvía a manos de una empresa que no rinde cuentas, y la soberanía del servicio de salud se erosiona.\n\nEn conclusión, la resolución no moderniza el hospital; entrega la gestión de limpieza y mantenimiento a una empresa privada, aumenta el gasto sin control y precariza al personal, dejando al pueblo trabajador sin garantía de un servicio digno."
  },
];
