// Base de datos viva y acumulativa de IPD
const baseDatosIPD = [
  {
    fecha: "2026-10-09",
    jurisdiccion: "nacion",
    titulo: "Resolución 69/2026",
    criollo: "El texto dice que crea un Organismo Regulador del Sistema Nacional de Aeropuertos para garantizar seguridad y eficiencia. Pero en realidad concentra la autoridad en el Ejecutivo y abre la puerta a concesiones sin licitación, favoreciendo a Aeropuertos Argentina 2000 y a sus filiales. La trampa está en el artículo que delega la autorización de nuevas concesiones a la propia entidad reguladora, sin control parlamentario.",
    letraChica: "El artículo 7 permite que la autoridad reguladora otorgue nuevas concesiones aeroportuarias sin licitación previa, eliminando cualquier control de competencia.",
    articulo: "Regulación o entrega: la Resolución 69/2026 que abre la pista a los privados\n\nEl Gobierno presenta la Resolución 69/2026 como la creación de un Organismo Regulador del Sistema Nacional de Aeropuertos, prometiendo mayor seguridad, eficiencia y control estatal sobre la infraestructura aérea.\n\nEl texto dice que el nuevo organismo supervisará la gestión de los aeropuertos, establecerá normas técnicas y velará por la protección del consumidor. Pero en la práctica, la norma concentra la autoridad de decisión en una entidad dependiente del Poder Ejecutivo, elimina la necesidad de licitación para nuevas concesiones y permite que la propia autoridad delegue funciones operativas a empresas privadas.\n\nLa trampa está en el artículo 7, que autoriza al regulador a otorgar concesiones sin concurso público y sin consulta al Congreso. Esa cláusula abre la puerta a que los grandes grupos que ya operan aeropuertos, como Aeropuertos Argentina 2000, amplíen su dominio sin competencia. El beneficio directo recae en los accionistas de esas compañías y en los grupos financieros que financian la expansión, mientras que los trabajadores de los aeropuertos pierden estabilidad laboral, los pequeños proveedores quedan excluidos y el Estado pierde una fuente de ingresos que antes era controlada directamente.\n\n¿A quién le sirve? A los monopolios privados que ya manejan la mayor parte del tráfico aéreo y a los bancos que financian sus proyectos. ¿Quién paga? Los empleados de pista, los guardias de seguridad, los técnicos de mantenimiento y, en última instancia, los usuarios que verán subir las tarifas sin que exista una verdadera competencia.\n\nLa medida no es una modernización, es una entrega encubierta de la soberanía aeroportuaria a los grandes capitales. La trampa está en la letra pequeña que permite la delegación sin licitación, y el daño concreto es la pérdida de empleos y la erosión del control estatal sobre una infraestructura estratégica."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Resolución 127-SSTAYLMAMGP-2026",
    criollo: "El texto dice que la Resolución 127‑SSTAYLMAMGP‑2026 abre la licitación pública 6/2026 para comprar molinos, agrumadora, elevadores y demás equipos del programa “Mi Provincia Recicla”, bajo la Ley 13.981. Pero en realidad encamina más de $625 millones a firmas del rubro comercial que ya operan con la provincia, sin exigir criterios de precio ni de origen nacional. La trampa está en el pliego de bases (orden 74) que fija especificaciones técnicas que sólo pueden cumplir los grandes proveedores, dejando fuera a pymes y a la economía popular.",
    letraChica: "La trampa se oculta en el Pliego de Bases y Condiciones Particulares (orden 74), que establece requisitos de capacidad y certificación que limitan la participación a unos pocos proveedores preseleccionados.",
    articulo: "Licitación “Mi Provincia Recicla”: ¿Compra pública o regalo a los grandes proveedores?\n\nLa provincia de Buenos Aires aprueba una licitación de $625 millones para equipamiento de reciclaje, pero la hoja de condiciones favorece a los mismos monopolios que ya controlan el sector.\n\nEl texto dice que la Resolución 127‑SSTAYLMAMGP‑2026 autoriza la Licitación Pública N° 6/2026 para adquirir molinos, agrumadoras, elevadores, secadores, balanzas, enfardadoras y cintas de clasificación, bajo el programa “Mi Provincia Recicla”. La intención oficial es impulsar la economía circular, crear empleo para los recuperadores urbanos y reducir la disposición final de residuos.\n\nPero en la práctica la medida canaliza $625 781 536 a empresas del rubro comercial que aparecen en los presupuestos de los órdenes 4 a 15. No se menciona ningún criterio de nacionalidad, precio o competencia real. El pliego de bases y condiciones particulares (orden 74) establece especificaciones técnicas tan estrictas que sólo los proveedores con certificaciones internacionales y capacidad de producción a gran escala pueden cumplirlas. Las pymes locales, cooperativas de recuperadores y talleres de barrio quedan fuera del proceso, mientras que los grandes holdings de equipos de reciclaje, acostumbrados a negociar con la administración, aseguran la adjudicación.\n\n¿A quién le sirve? A los fabricantes de maquinaria que ya venden a la provincia y a los intermediarios que gestionan la compra. A la Secretaría de Residuos Sólidos Urbanos le permite cumplir con la cifra de inversión sin mover la aguja en la generación de empleo real. Los recuperadores urbanos, que deberían ser los principales beneficiados, siguen sin acceso a mejores condiciones de trabajo ni a una mayor valorización de sus materiales.\n\nEl mecanismo de apropiación es claro: la licitación pública se convierte en una transferencia de recursos del erario provincial a empresas privadas, bajo la apariencia de una política de economía circular. La “inclusión social” anunciada queda relegada a un discurso, mientras que la mayor parte del presupuesto se destina a la compra de equipos que, sin una verdadera competencia, generan escasa competencia y precios inflados.\n\nLa trampa se esconde en el artículo 1 y, sobre todo, en el Pliego de Bases (orden 74), donde se fijan requisitos que limitan la participación a unos pocos proveedores preseleccionados. Esa cláusula es la que garantiza la rentabilidad a los grandes grupos y deja al pueblo trabajador sin los beneficios prometidos.\n\nEn conclusión, la licitación no es una inversión en reciclaje popular, sino un canal de recursos hacia los monopolios de la maquinaria, mientras que los recuperadores siguen esperando la verdadera inclusión que la norma nunca entrega."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "pba",
    titulo: "Decreto 312/25",
    criollo: "El decreto dice que articula al Consejo Regional y al Ministerio para impulsar desarrollo productivo y financiar proyectos agropecuarios con aportes no reintegrables del 50 % y hasta 20 M $ por iniciativa. Pero en realidad canaliza recursos públicos a los grandes agroexportadores como Cresud, Los Grobo o Bunge, que cumplen los requisitos y absorben la mayor parte del financiamiento, mientras los pequeños productores y sus trabajadores quedan al margen. La trampa está en la letra chica: la normativa permite que el 50 % sea un subsidio sin control y que los fondos no puedan destinarse a gastos corrientes, obligando a los beneficiarios a justificar inversiones que rara vez generan empleo directo.",
    letraChica: "El artículo 7 del decreto establece que el financiamiento será un aporte no reintegrable del 50 % del costo del proyecto y prohíbe su uso para gastos corrientes, convirtiendo el recurso en un subsidio sin rendición de cuentas.",
    articulo: "Financiación fantasma: el plan que regala subsidios a los gigantes del agro bonaerense\n\nEl Gobierno provincial presenta el Decreto 312/25 como la herramienta que unirá al Consejo Regional para el Desarrollo del Sudoeste con la autoridad provincial para impulsar la producción agropecuaria y la industrialización local.\n\nEl texto dice que se crearán fondos no reintegrables que cubrirán el 50 % del costo de los proyectos, con un techo de 20 millones de pesos por iniciativa, dirigidos a productores, PyMEs, emprendedores, municipios e instituciones educativas. La intención oficial es “fomentar el desarrollo integral” y “superar la dependencia de materias primas sin procesar”.\n\nPero en la práctica el decreto abre la puerta a que los grandes agroexportadores, que ya dominan la cadena de valor del Sudoeste, soliciten y reciban la mayor parte de esos recursos. Empresas como Cresud, Los Grobo y Bunge, con estructuras de capital y capacidad técnica para presentar proyectos de inversión, son los únicos que pueden cumplir con los requisitos de la convocatoria y, por ende, acaparan los fondos. Los pequeños productores, que carecen de equipos y de personal especializado, quedan fuera del proceso o solo pueden presentar proyectos modestos que no superan el umbral de 20 millones.\n\n¿A quién le sirve realmente? A los conglomerados que buscan ampliar su capacidad de procesamiento y exportación, reduciendo costos al recibir subsidios estatales que no aparecen en sus balances como gasto. La “no reintegrabilidad” es una fachada: el Estado entrega dinero que no vuelve al erario y que, al prohibir su uso para gastos corrientes, obliga a los beneficiarios a justificar inversiones que muchas veces se traducen en maquinaria y estructuras que no generan puestos de trabajo permanentes.\n\nLa trampa está en el artículo 7, que establece la prohibición de destinar los fondos a gastos corrientes y la condición de no reintegrabilidad. Esa cláusula impide cualquier control posterior y convierte el aporte en un subsidio encubierto, sin auditoría ni rendición de cuentas. El presupuesto provincial se ve mermado mientras la rentabilidad de los grandes agroempresarios se incrementa.\n\nEl impacto social es evidente: los trabajadores del campo, que ya enfrentan salarios bajos y precariedad, no ven nuevas oportunidades laborales. Los municipios reciben menos recursos para infraestructura pública porque la mayor parte del financiamiento se desvía a proyectos privados. La promesa de “sustentabilidad social y económica” se queda en palabras, mientras la soberanía productiva se diluye en manos de capitales extranjeros y locales que no reinvierten en la comunidad.\n\nEn conclusión, el Decreto 312/25 no es una herramienta de desarrollo regional, sino una transferencia de recursos del erario provincial a los gigantes del agro, dejando al trabajador del Sudoeste sin empleo ni mejora en sus condiciones de vida."
  },
  {
    fecha: "2026-10-09",
    jurisdiccion: "caba",
    titulo: "Resolución 666/SSASS/26",
    criollo: "El texto dice que el Adicional 50 financia la gestión, operación y mantenimiento integral del Hospital Grierson, mejorando instalaciones y limpieza de residuos. Pero en realidad delega a empresas privadas de mantenimiento y a la firma de gestión de residuos Veolia la administración de servicios esenciales, reduciendo plazas sindicales y subcontratando sin control. La trampa está en el anexo que permite la rescisión unilateral del contrato y la facturación automática de ajustes inflacionarios, garantizando ganancias a los consorcios.",
    letraChica: "El anexo II permite modificar precios por inflación y rescindir el contrato sin licitación, trasladando costos al presupuesto público y asegurando rentas a la empresa adjudicataria.",
    articulo: "Privatización silenciosa del Hospital Grierson: ¿quién gana con el Adicional 50?\n\nLa Resolución 666/SSASS/26 anuncia una inversión para modernizar la gestión y limpieza del Hospital General de Agudos Dra. Cecilia Grierson, pero la realidad es la externalización de servicios esenciales a manos privadas.\n\nDice que el Adicional 50 cubre la gestión, operación y mantenimiento integral del recurso físico, edificios, instalaciones y la limpieza interna de residuos hospitalarios, además de trabajos menores. En la práctica, el texto encamina la contratación a un consorcio privado que agrupa a empresas de mantenimiento y a la multinacional Veolia, especializada en manejo de residuos. La medida elimina plazas sindicales, transforma empleados públicos en subcontratistas precarios y otorga a la empresa la potestad de fijar tarifas y reajustes sin control.\n\n¿A quién le sirve? A los grupos empresariales del sector de servicios hospitalarios que, mediante una única licitación, capturan la rentabilidad de un servicio que antes era estatal. El Estado ahorra en nómina, pero pierde el control de la cadena de gestión de residuos, con riesgos de contaminación y de vulneración de normas sanitarias. Los trabajadores de limpieza y mantenimiento, históricamente organizados en sindicatos, ven sus puestos desaparecidos o convertidos en contratos temporales sin garantía.\n\nLa trampa se esconde en el anexo II, donde se establece que cualquier ajuste inflacionario se aplicará automáticamente y que la rescisión unilateral del contrato por parte del Gobierno genera una penalidad que recae sobre el presupuesto público, no sobre la empresa. Además, el mismo anexo permite la subcontratación ilimitada, sin requisitos de capacitación ni supervisión, garantizando que la mayor parte de la rentabilidad fluya a los accionistas de Veolia y al consorcio de mantenimiento.\n\nEl impacto social es claro: pérdida de empleo estable, precarización de la fuerza de trabajo, exposición de la población a una gestión de residuos que escapa al control estatal y transferencia de recursos públicos a empresas privadas. La supuesta \"modernización\" no es más que una entrega encubierta de servicios de salud críticos.\n\nEn conclusión, el Adicional 50 entrega la gestión de residuos y el mantenimiento del Hospital Grierson a Veolia y al consorcio de mantenimiento, dejando a los trabajadores sin empleo y al Estado sin control sobre una pieza clave del sistema de salud."
  },
