backend:
  name: github
  repo: ipdboletin/ipdboletin.github.io
  branch: main
  base_url: https://sveltia-cms-auth.ipd-boletin.workers.dev

media_folder: "blog/img"
public_folder: "/blog/img"

locale: es

collections:
  - name: "entradas"
    label: "Entradas del Blog"
    label_singular: "Entrada"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "Copete", name: "excerpt", widget: "text", hint: "1-2 líneas que resumen la nota." }
      - { label: "Imagen de cabecera", name: "image", widget: "image", required: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
